/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'subjectId' : IDL.Text,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'answer' : IDL.Text,
  'questionText' : IDL.Text,
  'subjectId' : IDL.Text,
});

export const idlService = IDL.Service({
  'addNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Int], [IDL.Nat], []),
  'addQuestion' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
  'getNotesBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
  'getQuestionsBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'isValidSubject' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'updateNote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateQuestion' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'subjectId' : IDL.Text,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'answer' : IDL.Text,
    'questionText' : IDL.Text,
    'subjectId' : IDL.Text,
  });
  
  return IDL.Service({
    'addNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'addQuestion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
    'getNotesBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
    'getQuestionsBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'isValidSubject' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'updateNote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateQuestion' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };