/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Note {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'subjectId' : string,
}
export interface Question {
  'id' : bigint,
  'createdAt' : bigint,
  'answer' : string,
  'questionText' : string,
  'subjectId' : string,
}
export interface _SERVICE {
  'addNote' : ActorMethod<[string, string, string, bigint], bigint>,
  'addQuestion' : ActorMethod<[string, string, string, bigint], bigint>,
  'deleteNote' : ActorMethod<[bigint], undefined>,
  'deleteQuestion' : ActorMethod<[bigint], undefined>,
  'getNotesBySubject' : ActorMethod<[string], Array<Note>>,
  'getQuestionsBySubject' : ActorMethod<[string], Array<Question>>,
  'isValidSubject' : ActorMethod<[string], boolean>,
  'updateNote' : ActorMethod<[bigint, string, string], undefined>,
  'updateQuestion' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];